name: Release Build Ubuntu Latest

on: pull_request

jobs:
  setup:
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: ${{github.workspace}}/build
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

      - name: Pull submodules
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -qq -y --no-install-recommends cmake clang build-essential cppcheck libsuitesparse-dev libeigen3-dev libomp-dev python3.10 libopencv-dev python3-opencv

      - name: Install pre-commit
        run: |
          pip3 install pre-commit

      - name: Install Pangolin dependencies
        run: |
          sudo apt install -qq -y --no-install-recommends libgl1-mesa-dev
          sudo apt install -qq -y --no-install-recommends libglew-dev

      - name: Install Pangolin
        run: |
          git clone https://github.com/stevenlovegrove/Pangolin.git
          cd Pangolin
          git checkout d484494
          mkdir build
          cd build
          cmake ..
          make -j
          sudo make install

      - name: Install GTSAM 4.2
        run: |
          sudo add-apt-repository ppa:borglab/gtsam-release-4.2
          sudo apt-get update
          sudo apt-get install libgtsam-dev libgtsam-unstable-dev



      - name: Create build directory
        run: cmake -E make_directory ${{ env.BUILD_DIR }}

      - name: Configure Cmake
        run: cmake -S . -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=Release -Wno-dev

      - name: Build
        run: cmake --build ${{ env.BUILD_DIR }} -j

      - name: Running tests
        run: |
          cd ${{ env.BUILD_DIR }}
          ./bin/tests
